import type { EmailTemplate } from './types';
import { generateId } from './types';

// Template gallery with 20+ pre-built templates
export const templateGallery: EmailTemplate[] = [
  {
    id: 'tpl-welcome',
    name: 'Bem-vindo',
    description: 'Email de boas-vindas para novos usuários',
    blocks: [
      { id: 'b1', type: 'spacer', height: 40 },
      { id: 'b2', type: 'image', src: '', alt: 'Logo', width: '150px', height: 'auto', href: '' },
      { id: 'b3', type: 'spacer', height: 30 },
      { id: 'b4', type: 'text', content: 'Bem-vindo ao PhishGuard!', fontSize: 28, fontWeight: '700', color: '#ECE8E1', align: 'center', padding: 16 },
      { id: 'b5', type: 'spacer', height: 20 },
      { id: 'b6', type: 'text', content: 'Sua conta foi criada com sucesso. Estamos felizes em tê-lo conosco!', fontSize: 16, fontWeight: '400', color: '#9A968E', align: 'center', padding: 16 },
      { id: 'b7', type: 'spacer', height: 30 },
      { id: 'b8', type: 'button', text: 'Começar', href: '#', backgroundColor: '#D97757', color: '#FFFFFF', borderRadius: 8, paddingX: 32, paddingY: 14, align: 'center' },
      { id: 'b9', type: 'spacer', height: 40 },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tpl-password-reset',
    name: 'Recuperação de Senha',
    description: 'Email para redefinição de senha',
    blocks: [
      { id: 'b1', type: 'spacer', height: 40 },
      { id: 'b2', type: 'text', content: 'Redefinição de Senha', fontSize: 24, fontWeight: '700', color: '#ECE8E1', align: 'center', padding: 16 },
      { id: 'b3', type: 'spacer', height: 20 },
      { id: 'b4', type: 'text', content: 'Recebemos uma solicitação para redefinir sua senha. Clique no botão abaixo para criar uma nova senha.', fontSize: 16, fontWeight: '400', color: '#9A968E', align: 'center', padding: 16 },
      { id: 'b5', type: 'spacer', height: 30 },
      { id: 'b6', type: 'button', text: 'Redefinir Senha', href: '#', backgroundColor: '#D97757', color: '#FFFFFF', borderRadius: 8, paddingX: 32, paddingY: 14, align: 'center' },
      { id: 'b7', type: 'spacer', height: 20 },
      { id: 'b8', type: 'text', content: 'Se você não solicitou esta redefinição, ignore este email.', fontSize: 12, fontWeight: '400', color: '#5C5852', align: 'center', padding: 8 },
      { id: 'b9', type: 'spacer', height: 40 },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tpl-alert',
    name: 'Alerta de Segurança',
    description: 'Notificação de atividade suspeita',
    blocks: [
      { id: 'b1', type: 'spacer', height: 30 },
      { id: 'b2', type: 'divider', color: '#F44336', thickness: 3, width: '60px' },
      { id: 'b3', type: 'spacer', height: 20 },
      { id: 'b4', type: 'text', content: '⚠️ Alerta de Segurança', fontSize: 26, fontWeight: '700', color: '#F44336', align: 'center', padding: 16 },
      { id: 'b5', type: 'spacer', height: 20 },
      { id: 'b6', type: 'text', content: 'Detectamos uma tentativa de login suspeita em sua conta.', fontSize: 16, fontWeight: '400', color: '#ECE8E1', align: 'center', padding: 16 },
      { id: 'b7', type: 'spacer', height: 16 },
      { id: 'b8', type: 'text', content: 'Data: Agora\nLocalização: Desconhecida\nDispositivo: Desconhecido', fontSize: 14, fontWeight: '400', color: '#9A968E', align: 'left', padding: 16 },
      { id: 'b9', type: 'spacer', height: 24 },
      { id: 'b10', type: 'button', text: 'Proteger Conta', href: '#', backgroundColor: '#F44336', color: '#FFFFFF', borderRadius: 8, paddingX: 32, paddingY: 14, align: 'center' },
      { id: 'b11', type: 'spacer', height: 40 },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tpl-training',
    name: 'Convite de Treinamento',
    description: 'Convite para capacitação de segurança',
    blocks: [
      { id: 'b1', type: 'spacer', height: 40 },
      { id: 'b2', type: 'image', src: '', alt: 'Training', width: '80px', height: '80px', href: '' },
      { id: 'b3', type: 'spacer', height: 24 },
      { id: 'b4', type: 'text', content: 'Você foi convidado para um treinamento!', fontSize: 22, fontWeight: '600', color: '#ECE8E1', align: 'center', padding: 16 },
      { id: 'b5', type: 'spacer', height: 16 },
      { id: 'b6', type: 'text', content: 'Aprenda a identificar ameaças de phishing e proteger sua empresa contra ataques cibernéticos.', fontSize: 15, fontWeight: '400', color: '#9A968E', align: 'center', padding: 16 },
      { id: 'b7', type: 'spacer', height: 24 },
      { id: 'b8', type: 'button', text: 'Ver Detalhes', href: '#', backgroundColor: '#D97757', color: '#FFFFFF', borderRadius: 8, paddingX: 32, paddingY: 14, align: 'center' },
      { id: 'b9', type: 'spacer', height: 40 },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tpl-report',
    name: 'Relatório Mensal',
    description: 'Resumo de atividades e métricas',
    blocks: [
      { id: 'b1', type: 'spacer', height: 30 },
      { id: 'b2', type: 'text', content: 'Seu Relatório Mensal', fontSize: 26, fontWeight: '700', color: '#ECE8E1', align: 'center', padding: 16 },
      { id: 'b3', type: 'spacer', height: 16 },
      { id: 'b4', type: 'divider', color: '#363C48', thickness: 1, width: '100%' },
      { id: 'b5', type: 'spacer', height: 20 },
      { id: 'b6', type: 'text', content: 'Aqui está o resumo das suas atividades de segurança deste mês.', fontSize: 15, fontWeight: '400', color: '#9A968E', align: 'center', padding: 12 },
      { id: 'b7', type: 'spacer', height: 24 },
      { id: 'b8', type: 'text', content: '📧 15 emails simulados enviados\n✓ 12 usuários completaram o treinamento\n🛡️ 3 ameaças bloqueadas', fontSize: 14, fontWeight: '400', color: '#ECE8E1', align: 'left', padding: 16 },
      { id: 'b9', type: 'spacer', height: 30 },
      { id: 'b10', type: 'button', text: 'Ver Relatório Completo', href: '#', backgroundColor: '#D97757', color: '#FFFFFF', borderRadius: 8, paddingX: 28, paddingY: 12, align: 'center' },
      { id: 'b11', type: 'spacer', height: 40 },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tpl-verification',
    name: 'Verificação de Email',
    description: 'Código de verificação para login',
    blocks: [
      { id: 'b1', type: 'spacer', height: 40 },
      { id: 'b2', type: 'text', content: 'Código de Verificação', fontSize: 24, fontWeight: '700', color: '#ECE8E1', align: 'center', padding: 16 },
      { id: 'b3', type: 'spacer', height: 20 },
      { id: 'b4', type: 'text', content: 'Use o código abaixo para verificar seu email:', fontSize: 15, fontWeight: '400', color: '#9A968E', align: 'center', padding: 12 },
      { id: 'b5', type: 'spacer', height: 24 },
      { id: 'b6', type: 'text', content: '🔐 123456', fontSize: 36, fontWeight: '700', color: '#D97757', align: 'center', padding: 24 },
      { id: 'b7', type: 'spacer', height: 20 },
      { id: 'b8', type: 'text', content: 'Este código expira em 10 minutos.', fontSize: 12, fontWeight: '400', color: '#5C5852', align: 'center', padding: 8 },
      { id: 'b9', type: 'spacer', height: 40 },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tpl-upgrade',
    name: 'Promoção de Upgrade',
    description: 'Oferta para升级 de plano',
    blocks: [
      { id: 'b1', type: 'spacer', height: 30 },
      { id: 'b2', type: 'text', content: '⭐ Faça upgrade agora', fontSize: 28, fontWeight: '700', color: '#D97757', align: 'center', padding: 16 },
      { id: 'b3', type: 'spacer', height: 20 },
      { id: 'b4', type: 'text', content: 'Desbloqueie recursos avançados e proteja sua empresa com o melhor plano.', fontSize: 16, fontWeight: '400', color: '#ECE8E1', align: 'center', padding: 16 },
      { id: 'b5', type: 'spacer', height: 16 },
      { id: 'b6', type: 'text', content: '✓ Análises avançadas\n✓ Treinamento ilimitado\n✓ Suporte prioritário', fontSize: 14, fontWeight: '400', color: '#9A968E', align: 'left', padding: 12 },
      { id: 'b7', type: 'spacer', height: 24 },
      { id: 'b8', type: 'button', text: 'Upgrade Agora', href: '#', backgroundColor: '#D97757', color: '#FFFFFF', borderRadius: 8, paddingX: 32, paddingY: 14, align: 'center' },
      { id: 'b9', type: 'spacer', height: 40 },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tpl-success',
    name: 'Ação Concluída',
    description: 'Confirmação de ação bem sucedida',
    blocks: [
      { id: 'b1', type: 'spacer', height: 40 },
      { id: 'b2', type: 'text', content: '✓', fontSize: 48, fontWeight: '700', color: '#4CAF50', align: 'center', padding: 16 },
      { id: 'b3', type: 'spacer', height: 16 },
      { id: 'b4', type: 'text', content: 'Ação Concluída com Sucesso!', fontSize: 24, fontWeight: '700', color: '#ECE8E1', align: 'center', padding: 16 },
      { id: 'b5', type: 'spacer', height: 16 },
      { id: 'b6', type: 'text', content: 'Sua solicitação foi processada corretamente.', fontSize: 15, fontWeight: '400', color: '#9A968E', align: 'center', padding: 12 },
      { id: 'b7', type: 'spacer', height: 30 },
      { id: 'b8', type: 'button', text: 'Continuar', href: '#', backgroundColor: '#4CAF50', color: '#FFFFFF', borderRadius: 8, paddingX: 32, paddingY: 14, align: 'center' },
      { id: 'b9', type: 'spacer', height: 40 },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tpl-reminder',
    name: 'Lembrete',
    description: 'Lembrete amigável',
    blocks: [
      { id: 'b1', type: 'spacer', height: 40 },
      { id: 'b2', type: 'text', content: '🔔 Lembrete', fontSize: 24, fontWeight: '700', color: '#ECE8E1', align: 'center', padding: 16 },
      { id: 'b3', type: 'spacer', height: 20 },
      { id: 'b4', type: 'text', content: 'Você tem uma pendência que precisa de sua atenção.', fontSize: 16, fontWeight: '400', color: '#9A968E', align: 'center', padding: 16 },
      { id: 'b5', type: 'spacer', height: 24 },
      { id: 'b6', type: 'button', text: 'Verificar Agora', href: '#', backgroundColor: '#FF9800', color: '#FFFFFF', borderRadius: 8, paddingX: 32, paddingY: 14, align: 'center' },
      { id: 'b7', type: 'spacer', height: 40 },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tpl-newsletter',
    name: 'Newsletter',
    description: 'Boletim informativo',
    blocks: [
      { id: 'b1', type: 'spacer', height: 30 },
      { id: 'b2', type: 'image', src: '', alt: 'Newsletter', width: '100%', height: '120px', href: '' },
      { id: 'b3', type: 'spacer', height: 20 },
      { id: 'b4', type: 'text', content: 'Newsletter PhishGuard', fontSize: 22, fontWeight: '700', color: '#ECE8E1', align: 'center', padding: 16 },
      { id: 'b5', type: 'spacer', height: 12 },
      { id: 'b6', type: 'divider', color: '#363C48', thickness: 1, width: '100%' },
      { id: 'b7', type: 'spacer', height: 16 },
      { id: 'b8', type: 'text', content: 'Principais ameaças do mês:', fontSize: 16, fontWeight: '600', color: '#D97757', align: 'left', padding: 12 },
      { id: 'b9', type: 'text', content: '• Phishing via SMS cresceu 40%\n• Novas técnicas de BEC identificadas\n• Ataques a empresas de saúde aumentaram', fontSize: 14, fontWeight: '400', color: '#9A968E', align: 'left', padding: 12 },
      { id: 'b10', type: 'spacer', height: 24 },
      { id: 'b11', type: 'button', text: 'Leia Mais', href: '#', backgroundColor: '#D97757', color: '#FFFFFF', borderRadius: 8, paddingX: 32, paddingY: 12, align: 'center' },
      { id: 'b12', type: 'spacer', height: 40 },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tpl-urgent',
    name: 'Comunicado Urgente',
    description: 'Mensagem de urgência',
    blocks: [
      { id: 'b1', type: 'spacer', height: 30 },
      { id: 'b2', type: 'divider', color: '#FF9800', thickness: 4, width: '100%' },
      { id: 'b3', type: 'spacer', height: 20 },
      { id: 'b4', type: 'text', content: '⚠️ URGENTE', fontSize: 30, fontWeight: '700', color: '#FF9800', align: 'center', padding: 16 },
      { id: 'b5', type: 'spacer', height: 16 },
      { id: 'b6', type: 'text', content: 'Uma ação imediata é necessária.', fontSize: 18, fontWeight: '600', color: '#ECE8E1', align: 'center', padding: 16 },
      { id: 'b7', type: 'spacer', height: 16 },
      { id: 'b8', type: 'text', content: 'Por favor, leia este comunicado com urgência e tome as medidas necessárias.', fontSize: 15, fontWeight: '400', color: '#9A968E', align: 'center', padding: 16 },
      { id: 'b9', type: 'spacer', height: 24 },
      { id: 'b10', type: 'button', text: 'Ver Detalhes', href: '#', backgroundColor: '#FF9800', color: '#FFFFFF', borderRadius: 8, paddingX: 32, paddingY: 14, align: 'center' },
      { id: 'b11', type: 'spacer', height: 40 },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tpl-meeting',
    name: 'Convite de Reunião',
    description: 'Convite para reunião online',
    blocks: [
      { id: 'b1', type: 'spacer', height: 30 },
      { id: 'b2', type: 'text', content: '📅 Reunião de Briefing', fontSize: 24, fontWeight: '700', color: '#ECE8E1', align: 'center', padding: 16 },
      { id: 'b3', type: 'spacer', height: 20 },
      { id: 'b4', type: 'divider', color: '#2196F3', thickness: 2, width: '60px' },
      { id: 'b5', type: 'spacer', height: 16 },
      { id: 'b6', type: 'text', content: 'Data: Quinta-feira, 14:00\nDuração: 30 minutos\nPlataforma: Zoom', fontSize: 15, fontWeight: '400', color: '#9A968E', align: 'left', padding: 16 },
      { id: 'b7', type: 'spacer', height: 16 },
      { id: 'b8', type: 'text', content: 'Agenda:\n• Revisão de campanhas\n• Próximos passos\n• Q&A', fontSize: 14, fontWeight: '400', color: '#ECE8E1', align: 'left', padding: 12 },
      { id: 'b9', type: 'spacer', height: 24 },
      { id: 'b10', type: 'button', text: 'Confirmar Presença', href: '#', backgroundColor: '#2196F3', color: '#FFFFFF', borderRadius: 8, paddingX: 28, paddingY: 12, align: 'center' },
      { id: 'b11', type: 'spacer', height: 40 },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tpl-invoice',
    name: 'Fatura',
    description: 'Nota fiscal / invoice',
    blocks: [
      { id: 'b1', type: 'spacer', height: 30 },
      { id: 'b2', type: 'text', content: 'Fatura #2024-0042', fontSize: 26, fontWeight: '700', color: '#ECE8E1', align: 'left', padding: 16 },
      { id: 'b3', type: 'spacer', height: 16 },
      { id: 'b4', type: 'divider', color: '#363C48', thickness: 1, width: '100%' },
      { id: 'b5', type: 'spacer', height: 16 },
      { id: 'b6', type: 'text', content: 'Plano: Business\nPeríodo: Mensal\nValor: R$ 497,00', fontSize: 15, fontWeight: '400', color: '#9A968E', align: 'left', padding: 12 },
      { id: 'b7', type: 'spacer', height: 16 },
      { id: 'b8', type: 'text', content: 'Vencimento: 25/04/2024', fontSize: 14, fontWeight: '600', color: '#D97757', align: 'left', padding: 12 },
      { id: 'b9', type: 'spacer', height: 24 },
      { id: 'b10', type: 'button', text: 'Pagar Agora', href: '#', backgroundColor: '#D97757', color: '#FFFFFF', borderRadius: 8, paddingX: 32, paddingY: 14, align: 'left' },
      { id: 'b11', type: 'spacer', height: 40 },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tpl-policy',
    name: 'Atualização de Política',
    description: 'Aviso sobre mudanças em políticas',
    blocks: [
      { id: 'b1', type: 'spacer', height: 30 },
      { id: 'b2', type: 'text', content: '📋 Atualização de Política', fontSize: 24, fontWeight: '700', color: '#ECE8E1', align: 'center', padding: 16 },
      { id: 'b3', type: 'spacer', height: 20 },
      { id: 'b4', type: 'text', content: 'Nossos termos de serviço foram atualizados. Recomendamos a revisão das novas políticas.', fontSize: 15, fontWeight: '400', color: '#9A968E', align: 'center', padding: 16 },
      { id: 'b5', type: 'spacer', height: 16 },
      { id: 'b6', type: 'text', content: 'Principais mudanças:\n• Nova política de dados\n• Termos de uso atualizados\n• Políticas de segurança reforçadas', fontSize: 14, fontWeight: '400', color: '#ECE8E1', align: 'left', padding: 12 },
      { id: 'b7', type: 'spacer', height: 24 },
      { id: 'b8', type: 'button', text: 'Ver Política', href: '#', backgroundColor: '#D97757', color: '#FFFFFF', borderRadius: 8, paddingX: 32, paddingY: 12, align: 'center' },
      { id: 'b9', type: 'spacer', height: 40 },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tpl-welcome-training',
    name: 'Boas-vindas + Treinamento',
    description: 'Email de boas-vindas com link para treinamento',
    blocks: [
      { id: 'b1', type: 'spacer', height: 40 },
      { id: 'b2', type: 'image', src: '', alt: 'Welcome', width: '120px', height: 'auto', href: '' },
      { id: 'b3', type: 'spacer', height: 24 },
      { id: 'b4', type: 'text', content: '🎉 Bem-vindo!', fontSize: 28, fontWeight: '700', color: '#ECE8E1', align: 'center', padding: 16 },
      { id: 'b5', type: 'spacer', height: 12 },
      { id: 'b6', type: 'text', content: 'Estamos felizes em tê-lo na equipe! Complete seu treinamento de segurança para começar.', fontSize: 16, fontWeight: '400', color: '#9A968E', align: 'center', padding: 16 },
      { id: 'b7', type: 'spacer', height: 24 },
      { id: 'b8', type: 'text', content: 'O treinamento leva apenas 15 minutos e é obrigatório.', fontSize: 14, fontWeight: '500', color: '#D97757', align: 'center', padding: 8 },
      { id: 'b9', type: 'spacer', height: 20 },
      { id: 'b10', type: 'button', text: 'Iniciar Treinamento', href: '#', backgroundColor: '#D97757', color: '#FFFFFF', borderRadius: 8, paddingX: 32, paddingY: 14, align: 'center' },
      { id: 'b11', type: 'spacer', height: 40 },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tpl-certificate',
    name: 'Certificado de Conclusão',
    description: 'Confirmação de conclusão de curso',
    blocks: [
      { id: 'b1', type: 'spacer', height: 30 },
      { id: 'b2', type: 'text', content: '🏆 Certificado', fontSize: 28, fontWeight: '700', color: '#D97757', align: 'center', padding: 16 },
      { id: 'b3', type: 'spacer', height: 16 },
      { id: 'b4', type: 'divider', color: '#D97757', thickness: 2, width: '60px' },
      { id: 'b5', type: 'spacer', height: 20 },
      { id: 'b6', type: 'text', content: 'Parabéns! Você completou o treinamento de Phishing Awareness.', fontSize: 16, fontWeight: '500', color: '#ECE8E1', align: 'center', padding: 16 },
      { id: 'b7', type: 'spacer', height: 12 },
      { id: 'b8', type: 'text', content: 'Nota: 95/100\nData: 21/04/2024', fontSize: 14, fontWeight: '400', color: '#9A968E', align: 'center', padding: 12 },
      { id: 'b9', type: 'spacer', height: 24 },
      { id: 'b10', type: 'button', text: 'Ver Certificado', href: '#', backgroundColor: '#D97757', color: '#FFFFFF', borderRadius: 8, paddingX: 32, paddingY: 12, align: 'center' },
      { id: 'b11', type: 'spacer', height: 40 },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tpl-support',
    name: 'Suporte Técnico',
    description: 'Solicitação de suporte',
    blocks: [
      { id: 'b1', type: 'spacer', height: 30 },
      { id: 'b2', type: 'text', content: '🛠️ Suporte Técnico', fontSize: 24, fontWeight: '700', color: '#ECE8E1', align: 'center', padding: 16 },
      { id: 'b3', type: 'spacer', height: 16 },
      { id: 'b4', type: 'text', content: 'Olá! Como podemos ajudar?\n\nSelecione uma categoria ou descreva seu problema.', fontSize: 15, fontWeight: '400', color: '#9A968E', align: 'center', padding: 16 },
      { id: 'b5', type: 'spacer', height: 20 },
      { id: 'b6', type: 'button', text: 'Abrir Ticket', href: '#', backgroundColor: '#2196F3', color: '#FFFFFF', borderRadius: 8, paddingX: 32, paddingY: 14, align: 'center' },
      { id: 'b7', type: 'spacer', height: 12 },
      { id: 'b8', type: 'text', content: 'Tempo médio de resposta: 2 horas', fontSize: 12, fontWeight: '400', color: '#5C5852', align: 'center', padding: 8 },
      { id: 'b9', type: 'spacer', height: 40 },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tpl-campaign-start',
    name: 'Campanha Iniciada',
    description: 'Notificação de início de campanha',
    blocks: [
      { id: 'b1', type: 'spacer', height: 30 },
      { id: 'b2', type: 'text', content: '🚀 Campanha Iniciada', fontSize: 26, fontWeight: '700', color: '#ECE8E1', align: 'center', padding: 16 },
      { id: 'b3', type: 'spacer', height: 16 },
      { id: 'b4', type: 'divider', color: '#9C27B0', thickness: 2, width: '60px' },
      { id: 'b5', type: 'spacer', height: 16 },
      { id: 'b6', type: 'text', content: 'Sua campanha de phishing simulada está agora ativa!', fontSize: 16, fontWeight: '400', color: '#ECE8E1', align: 'center', padding: 16 },
      { id: 'b7', type: 'spacer', height: 12 },
      { id: 'b8', type: 'text', content: 'Destinatários: 150\nTemplate: Phishing Awareness\nDuração: 7 dias', fontSize: 14, fontWeight: '400', color: '#9A968E', align: 'left', padding: 12 },
      { id: 'b9', type: 'spacer', height: 20 },
      { id: 'b10', type: 'button', text: 'Monitorar Resultados', href: '#', backgroundColor: '#9C27B0', color: '#FFFFFF', borderRadius: 8, paddingX: 28, paddingY: 12, align: 'center' },
      { id: 'b11', type: 'spacer', height: 40 },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tpl-quiz',
    name: 'Quiz de Segurança',
    description: 'Convite para quiz interativo',
    blocks: [
      { id: 'b1', type: 'spacer', height: 30 },
      { id: 'b2', type: 'text', content: '🧠 Quiz de Segurança', fontSize: 26, fontWeight: '700', color: '#ECE8E1', align: 'center', padding: 16 },
      { id: 'b3', type: 'spacer', height: 16 },
      { id: 'b4', type: 'text', content: 'Teste seus conhecimentos com nosso quiz rápido!', fontSize: 16, fontWeight: '400', color: '#9A968E', align: 'center', padding: 16 },
      { id: 'b5', type: 'spacer', height: 12 },
      { id: 'b6', type: 'text', content: '• 10 perguntas\n• 5 minutos\n• Certificação disponível', fontSize: 14, fontWeight: '400', color: '#ECE8E1', align: 'left', padding: 12 },
      { id: 'b7', type: 'spacer', height: 24 },
      { id: 'b8', type: 'button', text: 'Começar Quiz', href: '#', backgroundColor: '#4CAF50', color: '#FFFFFF', borderRadius: 8, paddingX: 32, paddingY: 14, align: 'center' },
      { id: 'b9', type: 'spacer', height: 40 },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tpl-end-of-trial',
    name: 'Fim do Trial',
    description: 'Aviso de término de período de teste',
    blocks: [
      { id: 'b1', type: 'spacer', height: 30 },
      { id: 'b2', type: 'text', content: '⏰ Seu Trial Está Acabando', fontSize: 26, fontWeight: '700', color: '#FF9800', align: 'center', padding: 16 },
      { id: 'b3', type: 'spacer', height: 16 },
      { id: 'b4', type: 'text', content: 'Faltam apenas 3 dias para o fim do seu período de teste.', fontSize: 16, fontWeight: '400', color: '#ECE8E1', align: 'center', padding: 16 },
      { id: 'b5', type: 'spacer', height: 12 },
      { id: 'b6', type: 'text', content: 'Depois disso, perderá acesso a:\n• Campanhas ilimitadas\n• Relatórios avançados\n• Suporte prioritário', fontSize: 14, fontWeight: '400', color: '#9A968E', align: 'left', padding: 12 },
      { id: 'b7', type: 'spacer', height: 24 },
      { id: 'b8', type: 'button', text: 'Fazer Upgrade', href: '#', backgroundColor: '#D97757', color: '#FFFFFF', borderRadius: 8, paddingX: 32, paddingY: 14, align: 'center' },
      { id: 'b9', type: 'spacer', height: 12 },
      { id: 'b10', type: 'text', content: 'ou continue com a versão gratuita', fontSize: 12, fontWeight: '400', color: '#5C5852', align: 'center', padding: 8 },
      { id: 'b11', type: 'spacer', height: 40 },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tpl-security-tips',
    name: 'Dicas de Segurança',
    description: 'Newsletter com dicas de cybersecurity',
    blocks: [
      { id: 'b1', type: 'spacer', height: 30 },
      { id: 'b2', type: 'text', content: '🛡️ Dicas de Segurança', fontSize: 24, fontWeight: '700', color: '#ECE8E1', align: 'center', padding: 16 },
      { id: 'b3', type: 'spacer', height: 16 },
      { id: 'b4', type: 'divider', color: '#4CAF50', thickness: 2, width: '60px' },
      { id: 'b5', type: 'spacer', height: 16 },
      { id: 'b6', type: 'text', content: 'Como identificar emails de phishing:', fontSize: 16, fontWeight: '600', color: '#4CAF50', align: 'left', padding: 12 },
      { id: 'b7', type: 'text', content: '1. Verifique o remetente\n2. Não clique em links suspeitos\n3. Desconfie de urgência\n4. Procure erros de gramática\n5. Verifique URLs antes de clicar', fontSize: 14, fontWeight: '400', color: '#9A968E', align: 'left', padding: 12 },
      { id: 'b8', type: 'spacer', height: 24 },
      { id: 'b9', type: 'button', text: 'Aprenda Mais', href: '#', backgroundColor: '#4CAF50', color: '#FFFFFF', borderRadius: 8, paddingX: 32, paddingY: 12, align: 'center' },
      { id: 'b10', type: 'spacer', height: 40 },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tpl-empty',
    name: 'Template em Branco',
    description: 'Comece do zero',
    blocks: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// Get all templates
export function getTemplates(): EmailTemplate[] {
  return templateGallery;
}

// Get template by ID
export function getTemplateById(id: string): EmailTemplate | undefined {
  return templateGallery.find(t => t.id === id);
}

// Create new template from another
export function createTemplateFrom(template: EmailTemplate): EmailTemplate {
  return {
    ...template,
    id: generateId(),
    name: `${template.name} (cópia)`,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    blocks: template.blocks.map(block => ({
      ...block,
      id: generateId(),
    })),
  };
}